# training_data.py
# RSU-specific annotated complaint corpus for SVM training

TRAINING_DATA = [

    # ─── ACADEMIC (category_id = 1) ───────────────────────────────
    ("My exam result was wrongly computed and my score is incorrect", "Academic"),
    ("The lecturer gave me an F grade but I attended all classes", "Academic"),
    ("I need to dispute my continuous assessment marks", "Academic"),
    ("My course registration was rejected without explanation", "Academic"),
    ("There is a timetable clash between two of my compulsory courses", "Academic"),
    ("The examination question was outside the course syllabus", "Academic"),
    ("My project supervisor has not responded to me in three months", "Academic"),
    ("I was absent from exam due to illness but was not given a makeup", "Academic"),
    ("My transcript shows a failed course I actually passed", "Academic"),
    ("The lecturer victimised me after I reported his behaviour", "Academic"),
    ("I need advice on course credit requirements for graduation", "Academic"),
    ("My semester result has not been uploaded on the portal", "Academic"),
    ("I was unfairly marked down in my final year project defence", "Academic"),
    ("The wrong grade was entered for my biochemistry examination", "Academic"),
    ("My carry-over course was not captured in my registration", "Academic"),
    ("I need help understanding my degree audit requirements", "Academic"),
    ("Academic calendar was changed without notifying students", "Academic"),
    ("I was denied entry into the examination hall without reason", "Academic"),
    ("My departmental advisor gave me wrong course advice", "Academic"),
    ("The result for my first semester has a serious error", "Academic"),

    # ─── WELFARE AND SECURITY (category_id = 2) ───────────────────
    ("A lecturer is demanding money before releasing my result", "Welfare and Security"),
    ("I was sexually harassed by a staff member on campus", "Welfare and Security"),
    ("Someone threatened me and I feel unsafe on campus", "Welfare and Security"),
    ("I am being blackmailed by a senior student", "Welfare and Security"),
    ("A lecturer asked me for sexual favours in exchange for marks", "Welfare and Security"),
    ("There was a fight in my hostel and security did nothing", "Welfare and Security"),
    ("I witnessed a theft on campus and want to report it", "Welfare and Security"),
    ("I am being bullied and intimidated by course mates", "Welfare and Security"),
    ("A staff member touched me inappropriately during an office visit", "Welfare and Security"),
    ("My personal safety is at risk due to cultism activities near campus", "Welfare and Security"),
    ("I received a threatening message from an unknown person", "Welfare and Security"),
    ("A lecturer is extorting students to pass his course", "Welfare and Security"),
    ("I feel emotionally unsafe and need counselling support", "Welfare and Security"),
    ("There was an assault incident in the faculty building", "Welfare and Security"),
    ("I need to report gender based violence by a university staff", "Welfare and Security"),
    ("My hostel room was broken into and my belongings stolen", "Welfare and Security"),
    ("A teaching assistant is harassing female students", "Welfare and Security"),
    ("Campus security allowed unauthorised persons into the building", "Welfare and Security"),
    ("I need urgent help regarding a welfare emergency", "Welfare and Security"),
    ("There is drug abuse happening openly in the student hostel", "Welfare and Security"),

    # ─── INFRASTRUCTURE (category_id = 3) ─────────────────────────
    ("The toilets in my faculty building have not been cleaned in weeks", "Infrastructure"),
    ("There is no electricity in the lecture hall for three days", "Infrastructure"),
    ("The classroom roof is leaking and damaging student property", "Infrastructure"),
    ("There is no running water in the student hostel", "Infrastructure"),
    ("The laboratory equipment is broken and class cannot proceed", "Infrastructure"),
    ("The internet connection in the library is not working", "Infrastructure"),
    ("Street lights on campus have been out for a month", "Infrastructure"),
    ("The road leading to the satellite campus is dangerously bad", "Infrastructure"),
    ("The hostel bathrooms are in a terrible state of disrepair", "Infrastructure"),
    ("Chairs and tables in the lecture room are broken", "Infrastructure"),
    ("The faculty generator has not been serviced and keeps failing", "Infrastructure"),
    ("The campus borehole is producing dirty water", "Infrastructure"),
    ("There is poor ventilation in the examination hall", "Infrastructure"),
    ("The disabled ramp at the faculty entrance is damaged", "Infrastructure"),
    ("Construction noise near the exam hall is disrupting students", "Infrastructure"),
    ("The projector in the main lecture theatre is not working", "Infrastructure"),
    ("Flooding in the campus car park is blocking access routes", "Infrastructure"),
    ("The campus clinic has run out of basic medical supplies", "Infrastructure"),
    ("Fire extinguishers in the building have not been serviced", "Infrastructure"),
    ("The lifts in the faculty building have been broken for months", "Infrastructure"),

    # ─── FINANCIAL (category_id = 4) ──────────────────────────────
    ("My scholarship payment has not been released this semester", "Financial"),
    ("I was charged twice for the same course registration fee", "Financial"),
    ("The bursary office rejected my payment receipt without reason", "Financial"),
    ("I need help with a fee waiver due to family financial hardship", "Financial"),
    ("My student loan application has not been processed", "Financial"),
    ("I paid my acceptance fee but it is not reflecting on the portal", "Financial"),
    ("There is an unexplained charge on my student fee statement", "Financial"),
    ("My department charged additional fees that are not on the schedule", "Financial"),
    ("I was not informed about a change in the tuition fee amount", "Financial"),
    ("My refund request for a cancelled course has not been processed", "Financial"),
    ("The bursary office is asking for payment before processing documents", "Financial"),
    ("I need a breakdown of all charges on my student account", "Financial"),
    ("My government bursary was credited to the wrong account", "Financial"),
    ("I have been wrongly marked as owing fees I have already paid", "Financial"),
    ("The financial aid office has not responded to my application", "Financial"),
    ("I need help appealing a fine that was incorrectly applied", "Financial"),
    ("My departmental dues payment is not showing on my clearance", "Financial"),
    ("I want to report an irregularity in the fee collection process", "Financial"),
    ("The payment portal charged me but did not generate a receipt", "Financial"),
    ("I paid my project fee but was told my payment was not received", "Financial"),

    # ─── GENERAL GUIDANCE (category_id = 5) ───────────────────────
    ("How do I apply for a student ID card replacement?", "General Guidance"),
    ("What is the deadline for course registration this semester?", "General Guidance"),
    ("Can you explain the process for applying for a deferment?", "General Guidance"),
    ("I need information about the graduation requirements for my department", "General Guidance"),
    ("How do I get a letter of introduction from the university?", "General Guidance"),
    ("What documents do I need for my industrial training placement?", "General Guidance"),
    ("I need guidance on how to apply for postgraduate admission", "General Guidance"),
    ("How do I access my academic transcript online?", "General Guidance"),
    ("Can I get information about the university counselling services?", "General Guidance"),
    ("I need help understanding the university examination rules", "General Guidance"),
    ("What is the procedure for changing my course of study?", "General Guidance"),
    ("How do I get approval for an outside course from another department?", "General Guidance"),
    ("I need advice on choosing elective courses for next semester", "General Guidance"),
    ("What is the process for obtaining a medical certificate of fitness?", "General Guidance"),
    ("How do I register for the NYSC mobilisation portal?", "General Guidance"),
    ("I need guidance about the university dress code policy", "General Guidance"),
    ("What are the requirements for applying for a hostel room?", "General Guidance"),
    ("How do I get my student clearance processed before convocation?", "General Guidance"),
    ("Can I get information about the university anti-plagiarism policy?", "General Guidance"),
    ("I need help understanding my rights as a student at RSU", "General Guidance"),
]